# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-25 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='appts',
            name='user',
        ),
        migrations.AddField(
            model_name='users',
            name='Bday',
            field=models.DateField(null=True, verbose_name='%Y-%m-%d'),
        ),
        migrations.DeleteModel(
            name='Appts',
        ),
    ]
