# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-25 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt2', '0002_auto_20180225_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='myList',
            field=models.ManyToManyField(related_name='Quotes_Listed', to='belt2.Users'),
        ),
    ]
